version: '3.8'
services:
  dynamodb-local:
    image: amazon/dynamodb-local
    ports:
      - "8000:8000"
    command: "-jar DynamoDBLocal.jar -sharedDb"
    networks:
      - go-dynamodb-crud-net

  api:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - dynamodb-local
    networks:
      - go-dynamodb-crud-net

networks:
  go-dynamodb-crud-net:
    driver: bridge