version: '3.8'

services:
  localstack:
    build:
      context: ./localstack
    environment:
      - SERVICES=dynamodb
    ports:
      - "4566:4566"

  myapp:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - localstack
    environment:
      - AWS_REGION=us-east-1
      - DYNAMODB_ENDPOINT=http://localstack:4566
